/**
 * IGDB 영문 태그(Genre/Theme) → 한글 매핑
 * DB 저장 시 사용자 경험 향상을 위해 한글로 변환
 */
export const TAG_TRANSLATIONS: Record<string, string> = {
  // Genres
  "Role-playing (RPG)": "RPG",
  "RPG": "RPG",
  Shooter: "슈팅",
  Adventure: "어드벤처",
  Platform: "플랫포머",
  Puzzle: "퍼즐",
  Racing: "레이싱",
  "Real Time Strategy (RTS)": "RTS",
  "RTS": "RTS",
  Strategy: "전략",
  "Turn-based strategy (TBS)": "턴제 전략",
  "TBS": "턴제 전략",
  Simulator: "시뮬레이션",
  Sport: "스포츠",
  Fighting: "대전 격투",
  Indie: "인디",
  Arcade: "아케이드",
  "Visual Novel": "비주얼 노벨",
  "Card & Board Game": "카드/보드",
  "Card and Board Game": "카드/보드",
  MOBA: "MOBA",
  "Point-and-click": "포인트 앤 클릭",
  "Point and click": "포인트 앤 클릭",
  Music: "리듬/음악",
  "Hack and slash/Beat 'em up": "핵 앤 슬래시",
  "Hack and slash": "핵 앤 슬래시",
  "Beat 'em up": "격투 액션",
  "Tactical": "전술",
  "Pinball": "핀볼",
  Quiz: "퀴즈",
  MMO: "MMO",
  "MMORPG": "MMORPG",

  // Themes
  Action: "액션",
  Fantasy: "판타지",
  "Science fiction": "SF",
  "Sci-fi": "SF",
  Horror: "공포",
  Survival: "생존",
  "Open world": "오픈 월드",
  Sandbox: "샌드박스",
  Stealth: "잠입",
  Comedy: "코미디",
  Drama: "드라마",
  Historical: "역사",
  Mystery: "미스터리",
  Thriller: "스릴러",
  Warfare: "전쟁",
  "4X (explore, expand, exploit, and exterminate)": "4X 전략",
  "4X": "4X 전략",
  Kids: "키즈",
  Party: "파티",
  Romance: "로맨스",
  "Erotic": "성인",
  "Non-fiction": "논픽션",
  Educational: "교육",
  "Turn-based": "턴제",
  "Real-time": "실시간",
  "Spectacle fighter": "스펙타클 격투",
  "Souls-like": "소울라이크",
  "Battle royale": "배틀 로얄",
  "First person": "1인칭",
  "Third person": "3인칭",
  "Isometric": "아이소메트릭",
  "Side view": "횡스크롤",
  "Top-down": "탑다운",
  "Mature": "성인",
  "Family": "가족",
}
